max_width = 132
ideal_width = 80
tab_spaces = 4
fn_call_width = 132
newline_style = "Unix"
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
impl_empty_single_line = true
fn_empty_single_line = true
fn_single_line = false
fn_return_indent = "WithArgs"
type_punctuation_density = "Wide"
single_line_if_else_max_width = 0
reorder_imports = true
reorder_imported_names = true
chains_overflow_last = false
